Create shift crud
Joannitka-pl/Roster pull request #7
Opened 2020-06-19 20:11 UTC by MonikaLukowska

@joaray proszę o CR

2020-06-22 11:21 UTC, joaray commented
> @joaray proszę o CR

nie musisz tego pisać ;) jak mnie oznaczysz prawidłowo, dostanę powiadomienie
tutaj powinno być:
resolves #7 
dzięki temu po zwerbowaniu issue się zamknie automatycznie

2020-06-22 11:23 UTC, joaray commented on app/controllers/shifts_controller.rb
> +      flash[:notice] = 'Shift was successfully created'
do locals - staramy się jak najmniej hardkodować :)

2020-06-22 11:24 UTC, joaray commented on app/controllers/shifts_controller.rb
> +  def show; end
zbędna metoda, nie chcemy oglądać pojedynczego dyżury

2020-06-22 11:24 UTC, joaray commented on app/controllers/shifts_controller.rb
> +  before_action :set_shift, only: %i[show edit update destroy]
bez show

2020-06-22 11:25 UTC, joaray commented on app/controllers/shifts_controller.rb
> +      redirect_to @shift
usuwamy show, więc musisz przekierować gdzie indziej, na razie niech to będzie widok wszystkich dyżurów

2020-06-22 11:26 UTC, joaray commented on app/controllers/shifts_controller.rb
> +    @shift.update(shift_params)
po co to rozdzielać? 
`if @shift.update(shift_params)`

2020-06-22 11:26 UTC, joaray commented on app/controllers/shifts_controller.rb
> +    if @shift.save
usunąć wtedy

2020-06-22 11:26 UTC, joaray commented on app/controllers/shifts_controller.rb
> +      redirect_to @shift
ponownie: nie będzie show, do index

2020-06-22 11:26 UTC, joaray commented on app/controllers/shifts_controller.rb
> +      flash[:notice] = 'Shift was successfully updated'
do locals

2020-06-22 11:35 UTC, joaray commented on app/controllers/shifts_controller.rb
> +    @shift.destroy
a gdzie to ma iść? przekieruj to gdzieś, bo w tej chwili zostaje na tam gdzie było, czyli na show, ale strona nie jest odświeżana, więc jak nawet zrobisz z poziomu index, to i tak nadal będziesz widoczny, jak chcesz mieć "problem" do rozwiązania, to "pozwalam zaszaleć": usuń tak, aby zniknęło bez odświeżania strony ;) ale usunięte musi zniknąć, a nie tak jak teraz, usuwa się, ale nadal widzę, chociaż nie ma ;)

2020-06-22 11:45 UTC, joaray commented on app/controllers/shifts_controller.rb
> +    params.require(:shift).permit(:date, :hour, :user_id, :studio)
a co takiego user_id? nie mam przecież usera

2020-06-22 11:46 UTC, joaray commented on app/views/shared/_errors.html.erb
> +<% if @shift.errors.any? %>
a gdzie to jest wyświetlane?

2020-06-22 11:48 UTC, joaray commented on app/views/shifts/_form.html.erb
> +      <%= f.select :hour, Shift.hours.keys.map {|time| [time.titleize, time]} %>
super, ale takie dane przygotowujemy w dekoratorze :)
wiem, że może być trochę za szybko, ale lepiej się od razu dobrze uczyć, w widokach tak mało logiki, jak się da

2020-06-22 11:48 UTC, joaray commented on app/views/shifts/_form.html.erb
> +       <%= f.select :studio, Shift.studios.keys.map {|studio| [studio.titleize,studio]} %>
jw, do dekoratora

2020-06-22 11:49 UTC, joaray commented on config/routes.rb
> +  resources :shifts
czy potrzebne nam są wszystkie?

2020-06-22 11:49 UTC, joaray commented on app/views/shifts/show.html.erb
> +<table>
tego widoku nie chcemy

2020-06-22 11:50 UTC, joaray commented on app/views/shifts/show.html.erb
> +<%= link_to 'Edit', edit_shift_path(@shift)%> | <%= link_to 'Delete', shift_path(@shift), method: :delete %>
a to przenieś na index

2020-06-22 11:50 UTC, joaray commented on app/views/shifts/new.html.erb
> +<h1>Add new shift</h1>
do locals

2020-06-22 11:50 UTC, joaray commented on app/views/shifts/edit.html.erb
> +<h1>Edit shift</h1>
do locals

2020-06-22 11:50 UTC, joaray commented on db/migrate/20200618134655_create_shifts.rb
> +      t.integer :user_id
ponownie: skąd to mam brac?

2020-06-22 11:51 UTC, joaray commented on app/views/shifts/_form.html.erb
> +       <%= f.select :user_id, %i[1 2 3] %>
nie tworzymy takich fikcji, nie ma usera, to nie ma

2020-06-22 11:52 UTC, joaray commented on app/views/shifts/show.html.erb
> +    <th>Studio</th>
wszystkie teksty do locals

2020-06-22 11:54 UTC, joaray commented on spec/models/shift_spec.rb
> +  it "is valid with a studio, hours, date and user_id" do
tutaj raczej przetestuj factory, po to je dodawałyśmy

2020-06-22 11:54 UTC, joaray commented on spec/models/shift_spec.rb
> +  it "is invalid without hours"
a to się zgubiło? ;)

2020-06-22 12:09 UTC, joaray commented on spec/models/shift_spec.rb
> +  it "is invalid with a duplicate combination of a studio, hours and date"
a masz taką walidację? na razie zostawmy, zrób, proszę, osobne issue na to co musi spełniać dyżur i w ramach tamtego issue doda się testy, teraz należy sprawdzić walidacje, ktore dodałaś w modelu

2020-06-22 14:37 UTC, joaray commented on app/models/shift.rb
> +  enum studio: %i[1 2 3]
to tak na razie zostawimy, ale docelowo nie powinno to tak wyglądać, poczytajcie, proszę, o enumach, wadach i zaletach, na co trzeba zwrócić uwagę itp

2020-06-24 20:26 UTC, joaray commented on app/controllers/shifts_controller.rb
> +  before_action :set_all_shifts, only: %i[ index update create destroy]
czemu tak?

2020-06-24 20:27 UTC, joaray commented on app/controllers/shifts_controller.rb
> +      redirect_to action: "index"
redirect_to shifts_path?

2020-06-24 20:29 UTC, joaray commented on app/decorators/shift_decorator.rb
> +    Shift.studios.keys.map {|studio| [studio.titleize,studio]}
Shift jest tu konieczne?

2020-06-24 20:31 UTC, joaray commented on app/views/shifts/_form.html.erb
> +      <br>
brrrr, nigdy tak nie rób ;) wiem, że nie mamy css, ale to trudno, odpuść wygląd, albo użyj css

2020-06-24 20:33 UTC, joaray commented on config/locales/en.yml
> +    edit_header_html: <h1>Edit shift</h1>
znaczniki html do widoku, tu teksty tylko

2020-06-24 20:33 UTC, joaray commented on app/controllers/shifts_controller.rb
> +    params.require(:shift).permit(:date, :hour, :user_id, :studio)
ostał się user, nadal ;)

2020-06-24 20:36 UTC, joaray commented on app/views/shifts/_form.html.erb
> +     <%= render 'shared/errors' %>
czemu tak błędy?

2020-06-24 20:41 UTC, joaray commented on app/views/shifts/index.html.erb
> +  <%= link_to 'Edit', edit_shift_path(shift) %> |
a czemu to jest pod tabelką, a nie w?

2020-06-24 20:41 UTC, joaray commented on app/views/shifts/index.html.erb
> +<% @shifts.each do |shift| %>
dla każdego dyżuru ma być osobna tabelka, czy chcesz utworzyć tabelkę, gdzie każdy kolejny jest wierszem?

2020-06-24 20:51 UTC, joaray commented on spec/models/shift_spec.rb
> +  it "is valid with a studio, hours, date and user_id" do
no to jak masz factory, to juz nie ma co ponownie sprawdzać, że jest prawidłowy ;)

2020-06-24 20:51 UTC, joaray commented on spec/models/shift_spec.rb
> +    expect(FactoryBot.build(:shift)).to be_valid
bez FactoryBot

2020-06-24 20:54 UTC, joaray commented on spec/factories/shifts.rb
> +    studio { Shift.studios.keys.sample }
tu proponuję jednak konkret, żeby było wiadomo jaki to dyżur

2020-06-24 20:54 UTC, joaray commented on spec/models/shift_spec.rb
> +    shift_first = create(
i wtedy tutaj wiesz jaki jest ten pierwszy, więc wystarczy utworzyć drugi taki sam, nawet również factorką

2020-06-25 14:03 UTC, MonikaLukowska commented on app/controllers/shifts_controller.rb
> +  before_action :set_all_shifts, only: %i[ index update create destroy]
aaa to niepotrzebna pozostałość po innej wersji moich rozwiazań:D tylko w index potrzebne, wiec usuwam metodę.

2020-06-25 14:03 UTC, MonikaLukowska commented on app/controllers/shifts_controller.rb
> +      redirect_to action: "index"
ok, zmieniam

2020-06-25 14:04 UTC, MonikaLukowska commented on app/decorators/shift_decorator.rb
> +    Shift.studios.keys.map {|studio| [studio.titleize,studio]}
wydaje mi się, że tak, bo odwołuję się do atrybutu danej klasy?

2020-06-25 14:04 UTC, MonikaLukowska commented on app/views/shifts/_form.html.erb
> +      <br>
wiem, to jest okropne, ale jeszcze bardziej raziła mnie pierwotna forma i planowałam to po prostu usunąć jak dojdziemy do css czy tam frameworkow jakichs typu bootstrap czy materialize

2020-06-25 14:04 UTC, MonikaLukowska commented on app/controllers/shifts_controller.rb
> +    params.require(:shift).permit(:date, :hour, :user_id, :studio)
no właśnie jeszcze w rspecu znalazlam w opisie:D

2020-06-25 14:06 UTC, MonikaLukowska commented on app/views/shifts/_form.html.erb
> +     <%= render 'shared/errors' %>
Masz na myśli sposób czy miejsce?Jeśli chodzi o sposób, to skorzystałam z https://guides.rubyonrails.org/active_record_validations.html i tu w p.8  jest opisane jak w widokach wyświetlać błędy validacji

2020-06-25 14:07 UTC, MonikaLukowska commented on app/views/shifts/index.html.erb
> +  <%= link_to 'Edit', edit_shift_path(shift) %> |
Wiesz co, ja w sumie jakoś nie pomyślałam, żeby wyświetlić to w sposób zbliżony do mockapow, tylko żeby po prostu wyświetlić, bo myślałam że później pewnie jakiś framework użyjemy i bedzie i tak trzeba na nowo wszystko poustawiać. Mam to zmienić?

2020-06-25 14:20 UTC, MonikaLukowska commented on app/views/shifts/index.html.erb
> +<% @shifts.each do |shift| %>
W sumie docelowo to ma być jakos na tygodnie pogrupowane w formie takiego planu tygodniowego. Jeszcze sie na tym nie skupiałam . Czy mam to wyświetlić w sposób jak najbardziej zbliżony do mockapów?

2020-06-25 14:20 UTC, MonikaLukowska commented on spec/models/shift_spec.rb
> +    shift_first = create(
czyli wtedy robię po prostu shift_first = create(:shift) shift_second = build(podaję to co podałam w factories)? I ten pierwszy shift przyjmuje wartości podane w factories?

2020-09-09 06:53 UTC, joaray commented on app/views/shifts/index.html.erb
> +<% @shifts.each do |shift| %>
Nie patrz na mockupy, ale niech to na każdym etapie ma sens ( nie musi być piękne, ale sensowne już tak). A tutaj dla mnie to nie ma, po co tworzysz tabelkę dla każdego dyżuru? jeśli chcemy wyświetlić wszystkie dyżury, na tę chwilę jeden pod drugim, to tworzysz tabelę, a poszczególne dyżury powinny być wierszami, prawda?

2020-09-09 06:56 UTC, joaray commented on app/views/shifts/index.html.erb
> +  <%= link_to 'Edit', edit_shift_path(shift) %> |
jw, dla każdego dyżuru tworzysz tabelę, ale przyciski do danego dyżuru umieszczasz pod tabelą, to by miało sens w widoku show ewentualnie, w indeksie nie bardzo, jak będziesz zmieniać, że dyżur jest w wierszu, to w tym samym umieść przyciski do niego, np w ostatniej kolumnie nazwanej "actions" albo coś podobnego

2020-09-09 06:58 UTC, joaray commented on config/routes.rb
> +  resources :shifts, except: [:show]
jak masz tylko :show, to nie potrzebna Ci tabela, a jeśli będziesz chciała w jakimś przypadku wyłączyć więcej, to np
```%i[show delete]```

2020-09-09 07:02 UTC, joaray commented on db/migrate/20200618134655_create_shifts.rb
> +      t.integer :user_id
Nie pamiętam czy rozmowę w tej kwestii prowadziłyśmy na placku czy nie, ale tutaj nie ma skąd tego brać, prawda. Nie możesz dodawać czegoś czego nie ma, tylko dlatego, że wiesz że będzie. Poza tym, to nie będzie integerem... 
I kolejna sprawa, masz walidacje w modelu, to tutaj też musi być zabezpieczenie.

2020-09-09 07:04 UTC, joaray commented on spec/factories/shifts.rb
> +      date  { "3rd Jul 2020" }
zrób to jako data jakoś sformatowana, a nie z ręki wpisany string

2020-09-09 07:07 UTC, joaray commented on spec/factories/shifts.rb
> +      hour { "1-6" }
To nie powinno być 1-6, jeśli dyżury mogą być różnej długości, to muszą mieć start_hour i end_hour, albo hour (jako start) i długość trwania, umieszczanie 2 informacji w jednym polu zawsze potem utrudnia ich wyciąganie, więc z punktu widzenia bazy danych, to koszmarek ;) musicie tutaj zdecydować ktore rozwiązanie przyjmujecie. Może być tak, że na tę chwilę, wszystkie dyżury są 8h i hour == start_hour, ale jeśli Asia już wie, że one są zupełnie różne, to bym dodała drugą informację (albo o ktorej się kończy, albo ile trwa)

2020-09-09 07:08 UTC, joaray commented on spec/features/shifts_spec.rb
> +    @shift = create(:shift)
nie twórz tutaj shiftu, jak poniżej sprawdzasz czy się tworzy

2020-09-09 07:09 UTC, joaray commented on spec/features/shifts_spec.rb
> +  end
dodaj jeszcze, że prawidłowo wyświetla, czyli, że widzisz studio, dzień i godziny

2020-09-09 07:10 UTC, joaray commented on spec/features/shifts_spec.rb
> +    expect(page).to have_content('New shift was successfully created')
a tutaj content nie da się jakoś dokładniej? chwilowo nie piszę w rspec, ale zawsze im dokładniej sprawdzisz tym lepiej, a tutaj to w ogóle szczególne miejsce, flash? albo coś, takie ogólne page to have content to trochę za mało

2020-09-09 07:10 UTC, joaray commented on spec/features/shifts_spec.rb
> +    }.to change(Shift, :count).by(1)
bardzo dobrze

2020-09-09 07:12 UTC, joaray commented on spec/features/shifts_spec.rb
> +    find(:xpath, "//a[@href='/shifts/#{@shift.id}/edit']").click
ja to bym jednak poszła na index i tam kliknęła po prostu, czyli zwykłe visit...

2020-09-09 07:12 UTC, joaray commented on spec/features/shifts_spec.rb
> +    expect {
tu też

2020-09-09 07:20 UTC, joaray commented on spec/models/shift_spec.rb
> +  it "is invalid without a studio" do
rób pojedynczy cudzysłów jeśli nie potrzebujesz podwójnego, rubocop nie wyłapał?

2020-09-09 07:21 UTC, joaray commented on spec/models/shift_spec.rb
> +end
bardzo dobrze

2020-09-09 08:01 UTC, joaray commented on spec/support/shared_db_connection.rb
> +  mattr_accessor :shared_connection
a do czego to?

2020-09-09 08:03 UTC, joaray commented on test/test_helper.rb
> -ENV['RAILS_ENV'] ||= 'test'
a to czemu pousuwane?

2020-10-12 11:04 UTC, MonikaLukowska commented on config/routes.rb
> +  resources :shifts, except: [:show]
ale tam jest "except" show a nie tylko dla show:)

2020-10-13 07:51 UTC, joaray commented on config/routes.rb
> +  resources :shifts, except: [:show]
nie o to chodziło, druga część to była ogólna uwaga, jak masz **wyłączone tylko** `show`, to nie potrzebna Ci tablica, czyli powinno być: `except: : show`, a jak masz więcej (nie tutaj, w ogóle), obojętnie czy z `only` czy z `except`, to zrobisz, np: `except: %i[show edit]`

2020-10-13 14:29 UTC, MonikaLukowska commented on config/routes.rb
> +  resources :shifts, except: [:show]
aaa ok, teraz kumam:)

2021-01-13 21:01 UTC, joaray commented on spec/models/shift_spec.rb
> +    shift_first = create(
tak

2021-01-20 11:36 UTC, MonikaLukowska commented on spec/features/shifts_spec.rb
> +    find(:xpath, "//a[@href='/shifts/#{@shift.id}/edit']").click
nie bardz wiem jak to zmienić, bo jestem na index, gdzie są wszystkie shifty a chcę edytować ten konkretny. Więc jak mam mu powiedzieć że ma kliknąć akurat na ten koknretny edit?

2021-01-20 11:40 UTC, MonikaLukowska commented on spec/support/shared_db_connection.rb
> +  mattr_accessor :shared_connection
a to się samo chyba zrobiło, bo nie kojarzę żebym ja to robiła

2021-01-27 09:55 UTC, joaray requested changes

2021-01-27 09:55 UTC, joaray commented on app/views/shifts/index.html.erb
> +<% @shifts.each do |shift| %>
Nadal masz tabelkę dla każdego dyżuru, poproszę jedną tabelkę, gdzie każdy dyżur będzie wierszem. Na końcu wiersza będą akcje: edit i delete. Dodawanie nowego dyżuru na samej górze, żeby jeśli zrobi się ich dużo nie trzeba było przewijać na dół.

2021-01-27 09:55 UTC, joaray commented on db/migrate/20200624102311_remove_user_from_shift.rb
> +class RemoveUserFromShift < ActiveRecord::Migration[6.0]
Są oczywiście różne strategie utrzymania kodu. Ale jeśli dodasz taką migrację, to ona zostanie w historii na zawsze i będzie to bardzo dziwnie i myląco wyglądać, bo nie będzie wiadomo po co był usuwany user. To jeszcze nie jest nigdzie zwerbowane, to Twoja robocza wersja, więc raczej wycofaj poprzednią migrację z userem (teraz już obie), i dodaj ją prawidłową. Co innego kiedy zmieniasz tabelę już zmergowaną, w której są jakieś dane, wtedy to jak najbardziej prawidłowe.
Wycofanie ostatniej migracji: `rails db:rollback`
https://edgeguides.rubyonrails.org/active_record_migrations.html#rolling-back

2021-01-27 09:55 UTC, joaray commented on spec/factories/shifts.rb
> +      date  { "3rd Jul 2020" }
nie widzę zmian

2021-01-27 09:55 UTC, joaray commented on spec/factories/shifts.rb
> +      hour { "1-6" }
nie widzę zmian

2021-01-27 09:55 UTC, joaray commented on spec/features/shifts_spec.rb
> +    @shift = create(:shift)
nie widzę zmian

2021-01-27 09:55 UTC, joaray commented on spec/features/shifts_spec.rb
> +    expect(page).to have_content('New shift was successfully created')
nie widzę zmian

2021-01-27 09:55 UTC, joaray commented on spec/features/shifts_spec.rb
> +    find(:xpath, "//a[@href='/shifts/#{@shift.id}/edit']").click
już wiesz?, bo na slacku pisałaś, że ogarnęłaś, czy ja nie widzę zmian?

2021-04-09 04:25 UTC, joaray approved these changes
Popraw te 2 ostatnie rzeczy (`dom_id` i `have_content`) i możesz mergować

2021-04-09 04:25 UTC, joaray commented on app/views/shifts/index.html.erb
> +      <tr class="shift_<%= shift.id %>">
https://apidock.com/rails/ActionView/RecordIdentifier/dom_id

2021-04-09 04:25 UTC, joaray commented on spec/features/shifts_spec.rb
> +  end
Nadal jest `have_content` a nie wiesz jaki, możesz po klasie, po id, po tagu
https://devhints.io/capybara

2021-05-05 15:12 UTC, MonikaLukowska commented
merge shift crud branch

2021-05-05 15:12 UTC, merged